# Generated by Django 2.0.4 on 2018-06-24 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=5000, null=True)),
                ('mrp', models.CharField(max_length=10, null=True)),
                ('discountprice', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
