Installation steps
-- OS Installations

to install libs git, zsh, ohmyzsh, autoenv and pyenv

`sudo apt-get install build-essential curl gdal-bin git libbz2-dev libgdbm-dev liblzma-dev libmagic1 libncurses5-dev libncursesw5-dev libreadline-dev libsqlite3-dev libssl-dev libssl-dev llvm make python-dev python3-dev python-gdal python3-gdal supervisor tk-dev wget xz-utils zlib1g-dev zsh`

`sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"`

`chsh -s $(which zsh)`

`git clone https://github.com/Tarrasch/zsh-autoenv ~/.dotfiles/lib/zsh-autoenv`

`echo 'source ~/.dotfiles/lib/zsh-autoenv/autoenv.zsh' >> ~/.zshrc`

`source ~/.zshrc`

`git clone https://github.com/pyenv/pyenv.git --depth 1 ~/.pyenv`

`echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.zshrc`

`echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.zshrc`

-- Python Installation

`pyenv install 3.6.4`

`echo "eval \"$(pyenv init -)\"" >> ~/.zshrc`


-- Node Installation


.Install Postgresql

. Create database wall_e

. Create user root with password root

. Create a local_settings.py file in directory src/proj/proj/



.Add this code
[source,python]
----
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'wall_e',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': 'localhost',
        'PORT': '5432'
    }
}
----
